### ISSUE TITLE
Host and Process Metrics not working with 2.18

### ISSUE THREAD

**Issue by ChethanUK** [kamon-io/Kamon#906]
When upraded to 2.18:
```bash
lazy val kamonVersion = "2.1.7"
lazy val kamonDeps = Seq(
  // Core: System, Executors
  kamon %% "kamon-system-metrics" % kamonVersion,
```

Both process and System metrics is not working 
```bash
Exception in thread "Process Metrics" java.lang.IncompatibleClassChangeError: Found interface oshi.software.os.OSProcess, but class was expected
	at kamon.instrumentation.system.process.ProcessMetricsCollector$MetricsCollectionTask.recordProcessCpu(ProcessMetricsCollector.scala:75)
	at kamon.instrumentation.system.process.ProcessMetricsCollector$MetricsCollectionTask.$anonfun$schedule$1(ProcessMetricsCollector.scala:62)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:660)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Exception in thread "Host Metrics" java.lang.NoSuchMethodError: 'oshi.software.os.OSFileStore[] oshi.software.os.FileSystem.getFileStores()'
	at kamon.instrumentation.system.host.HostMetricsCollector$InfrequentCollectionTask.recordStorageUsage(HostMetricsCollector.scala:164)
	at kamon.instrumentation.system.host.HostMetricsCollector$InfrequentCollectionTask.$anonfun$schedule$2(HostMetricsCollector.scala:130)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:660)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by SimunKaracic** [comment]
What version of scala are you using?

**Comment by ChethanUK** [comment]
Scala: 2.13 and Java: 11 [Tried with `openjdk:8-jdk` docker as well]

**Comment by SimunKaracic** [comment]
We have a pending PR which updates the `oshi` version, so we'll get that and the new release out the door ASAP. 

If the problem persists in `2.1.9`, I'll dig into it

**Comment by SimunKaracic** [comment]
Can you try this with `2.1.9`?

**Comment by ChethanUK** [comment]
> Can you try this with `2.1.9`?

Tried 2.1.9 but same problem

**Comment by ChethanUK** [comment]
Had to disable both: 
```bash
    process-metrics {
      enabled = no
    }
    host-metrics {
      enabled = no
    }
```

**Comment by SimunKaracic** [comment]
What version of JNA is on your classpath? 
This looks like you have a different version of JNA than the one OSHI wants. 
Can you check your dependency graph?

**Comment by ChethanUK** [comment]
![image](https://user-images.githubusercontent.com/16241795/101405778-9a822080-38fe-11eb-939c-4f1670d6d0b2.png)

Oshi Core Version is matching with https://github.com/kamon-io/Kamon/blob/master/project/Build.scala#L38

**Comment by SimunKaracic** [comment]
I don't understand. You have oshi-core as a dependency too? 

Can you search for jna as a dependency the same way you searched for `oshi-core`?

**Comment by ChethanUK** [comment]
Hi @SimunKaracic Pasting the sbt dependencyTree output:

```bash
[info]   | +-com.lightbend.lagom:lagom-scaladsl-api_2.13:1.6.4 [S]
[info]   | | +-com.lightbend.lagom:lagom-api_2.13:1.6.4 [S]
[info]   | | | +-com.fasterxml.jackson.core:jackson-annotations:2.10.4
[info]   | | | +-com.fasterxml.jackson.core:jackson-core:2.10.4
[info]   | | | +-com.fasterxml.jackson.core:jackson-databind:2.10.4
[info]   | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.10.4
[info]   | | | | +-com.fasterxml.jackson.core:jackson-core:2.10.4
....
[info]   |
[info]   +-io.kamon:kamon-prometheus_2.13:2.1.9 [S]
[info]   | +-com.squareup.okhttp3:okhttp:3.14.7
[info]   | | +-com.squareup.okio:okio:1.17.2
[info]   | |
[info]   | +-io.kamon:kamon-core_2.13:2.1.9 [S]
[info]   |   +-com.typesafe:config:1.3.1 (evicted by: 1.4.0)
[info]   |   +-com.typesafe:config:1.4.0
[info]   |   +-org.slf4j:slf4j-api:1.7.25 (evicted by: 1.7.30)
[info]   |   +-org.slf4j:slf4j-api:1.7.30
[info]   |
[info]   +-io.kamon:kamon-status-page_2.13:2.1.9 [S]
[info]   | +-io.kamon:kamon-core_2.13:2.1.9 [S]
[info]   |   +-com.typesafe:config:1.3.1 (evicted by: 1.4.0)
[info]   |   +-com.typesafe:config:1.4.0
[info]   |   +-org.slf4j:slf4j-api:1.7.25 (evicted by: 1.7.30)
[info]   |   +-org.slf4j:slf4j-api:1.7.30
[info]   |
[info]   +-io.kamon:kamon-system-metrics_2.13:2.1.9 [S]
[info]   | +-com.github.oshi:oshi-core:5.3.6
[info]   | | +-net.java.dev.jna:jna-platform:5.6.0
[info]   | | | +-net.java.dev.jna:jna:5.6.0
[info]   | | |
[info]   | | +-net.java.dev.jna:jna:5.6.0
[info]   | | +-org.slf4j:slf4j-api:1.7.30
[info]   | |
[info]   | +-io.kamon:kamon-core_2.13:2.1.9 [S]
[info]   |   +-com.typesafe:config:1.3.1 (evicted by: 1.4.0)
[info]   |   +-com.typesafe:config:1.4.0
[info]   |   +-org.slf4j:slf4j-api:1.7.25 (evicted by: 1.7.30)
[info]   |   +-org.slf4j:slf4j-api:1.7.30
[info]   |
[info]   +-net.java.dev.jna:jna-platform:5.6.0
[info]   | +-net.java.dev.jna:jna:5.6.0
[info]   |
[info]   +-net.java.dev.jna:jna:5.6.0
[info]   +-org.postgresql:postgresql:42.2.8
[info]   +-org.scalactic:scalactic_2.13:3.2.3 [S]
[info]     +-org.scala-lang:scala-reflect:2.13.0 [S]
[info]
```

**Comment by ChethanUK** [comment]
HI @SimunKaracic Wat can be done?

**Comment by SimunKaracic** [comment]
I'm loooking at it!

A reproduction sample would be helpful, since it's working for me with those same versions :/

**Comment by yarosman** [comment]
I have the same error running play-application in docker with java `adoptopenjdk/openjdk11:alpine-jre` and installed eudev
`Seq(Cmd("RUN", "apk add eudev"), cmd)`

**Comment by PavanaU** [comment]
> Seq(Cmd("RUN", "apk add eudev"), cmd)

@yarosman So `eudev` fixed the problem?

**Comment by SimunKaracic** [comment]
Did installing eudev clear the issue?

**Comment by yarosman** [comment]
@SimunKaracic No, I had already installed eudev. But I found the problem and solution for this exception in my case.
The problem was that oshi can't work with our /tmp folder on alpine in docker. We mounted /tmp folder in wrong way https://discuss.linuxcontainers.org/t/how-to-mount-tmp-as-tmpfs-in-alpine-linux/5070. After fixing mounting everything works fine with correct metrics reporting

**Comment by Pooriya-Shokri** [comment]
Is there any good news besides @yarosman  comment? experiencing the same here.

**Comment by SimunKaracic** [comment]
It's hard without a reproduction sample. The issue is with our `oshi` dependency, but without a repro there's not much we can do here.
Did following yarosmans steps help?

**Comment by Pooriya-Shokri** [comment]
Yes I've followed yarosmans, yet no outcome.
What can I do to help you with a reproduction sample?
I'm on Ubuntu 20, Oracle JDK 11 and Kamon 2.1.15.

**Comment by SimunKaracic** [comment]
Just a minimal app that displays the issue would be a great help. 
> I'm on Ubuntu 20, Oracle JDK 11 and Kamon 2.1.15.
I'm on Ubuntu as well, but I'm using OpenJDK 8 and 11 to test things. Can you see if using it fixes your issue?

**Comment by NathalyHernandez** [comment]
hello, I am currently using java version 11.0.19 from the public repository of **amazoncorretto:11.0.19-alpine** but but I am getting the same error 
<img width="817" alt="image" src="https://github.com/kamon-io/Kamon/assets/33837826/c9d3d605-663b-436d-b39e-a9ed42b76ae2">

I have tried with the following kamon libraries, but I have not been able to solve it, does anyone know about a possible solution?

"io.kamon"                         %% "kamon-bundle"                   % "2.1.17",
      "io.kamon"                         %% "kamon-jdbc"                     % "2.1.17",
      "io.kamon"                         %% "kamon-executors"                % "2.1.17",
      "io.kamon"                         %% "kamon-bundle"                   % "2.5.12",
      "io.kamon"                         %% "kamon-jdbc"                     % "2.5.12",
      "io.kamon"                         %% "kamon-executors"                % "2.5.12",
