### PR TITLE
Upgrade to stable tapir version

### PR DESCRIPTION
**Pull request by Grandys**
After upgrading tapir version in my project, from 0.20.2 to 1.0.1, I got an error:
```
Exception in thread "application-thread-3" java.lang.NoSuchMethodError: 'scala.Function2 sttp.tapir.server.ServerEndpoint.renderPathTemplate$default$1()'
	at kamon.instrumentation.tapir.TapirToRouteInterceptor$.$anonfun$toRoute$1(TapirInstrumentation.scala:48)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:25)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
```

This PR bumps tapir to latest version and fixes breaking changes, according to the [migration guide](https://github.com/softwaremill/tapir/blob/725daf79b4af3e47d50aad33919b221f5117326b/generated-doc/out/migrating.md#moved-traits-classes-objects)

### CODE REVIEW

**Comment by hughsimpson** [comment]
@ivantopo Can we get a review of this pr plz? I'd love to be able to upgrade to stable tapir

**Comment by ivantopo** [comment]
I'm wondering if there is any way in which we could make this backwards compatible, otherwise folks will need to upgrade both Tapir and Kamon at the same time :thinking:

**Comment by hughsimpson** [comment]
I think something like this works: https://github.com/Grandys/Kamon/pull/1 - but it's a little unpleasant (need to have two separate modules for the different tapir versions, to permit compilation of the differing method calls...)

**Comment by hughsimpson** [comment]
@ivantopo bump?

**Comment by ivantopo** [comment]
Hey @Grandys, I opened a [PR](https://github.com/Grandys/Kamon/pull/2) to your branch with a quick re-org of the code so we have it all in a single sbt module. Please take a look at let me know what you think!

**Comment by Grandys** [comment]
Thank you for PR @ivantopo, so now I am waiting for this PR to merged to the main branch :)

**Comment by ivantopo** [comment]
Thank you so much @Grandys and @hughsimpson for your help on this! :muscle:
