### ISSUE TITLE
Error after upgrade from 2.5.2 to 2.5.3

### ISSUE THREAD

**Issue by fggarcia** [kamon-io/Kamon#1171]
After upgrade:
```
val kamonVersion = "2.5.3"
val kanelaVersion = "1.0.14"

"io.kamon" %% "kamon-bundle" % kamonVersion,
"io.kamon" %% "kamon-prometheus" % kamonVersion,
"io.kamon" %% "kamon-zipkin" % kamonVersion,
"io.kamon" %% "kamon-jaeger" % kamonVersion,
"io.kamon" %% "kamon-status-page" % kamonVersion,
"io.kamon" % "kanela-agent" % kanelaVersion % "agent",
```

the error is only occurr only when i run ```sbt test```

```
akka.actor.ActorSystemImpl - Uncaught error from thread [hotels-metadata-store-test-akka.actor.default-dispatcher-8]: 'java.lang.String com.fasterxml.jackson.annotation.JsonProperty.namespace()', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[hotels-metadata-store-test]java.lang.NoSuchMethodError: 'java.lang.String com.fasterxml.jackson.annotation.JsonProperty.namespace()'
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findNameForDeserialization(JacksonAnnotationIntrospector.java:1330)
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForDeserialization(AnnotationIntrospectorPair.java:785)
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForDeserialization(AnnotationIntrospectorPair.java:785)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesColle ('127.0.0.1', 56977)
```

after rollback to kamon 2.5.2... ```sbt test``` work fine again.

## NOTE 

```sbt test``` initial output:
```
| |/ /               | |       \ \ \ \
| ' / __ _ _ __   ___| | __ _   \ \ \ \
|  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
| . \ (_| | | | |  __/ | (_| |  / / / /
|_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/

==============================
Running with Kanela, the Kamon Instrumentation Agent :: (v1.0.12)
```

I find that kamon-bundle has kanela-1.0.12.jar (when i inject  agent as jvm param -javaagent:/home/fede/Downloads/kanela-agent-1.0.14.jar when running app, the error not occur)

![image](https://user-images.githubusercontent.com/1306596/170167490-ff8bb470-99a7-47e8-8f44-523c748f4dd0.png)
